name: SQL Auto Grading - Alter Student Table

on:
  push:
  pull_request:

jobs:
  grade:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:

      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4


      # Step 2: Wait for MySQL
      - name: Wait for MySQL
        run: |
          for i in {1..30}
          do
            mysqladmin ping \
              -h 127.0.0.1 \
              -P 3306 \
              -u root \
              -proot && break
            sleep 2
          done


      # Step 3: Check MySQL
      - name: Check MySQL
        run: |
          mysql \
            -h 127.0.0.1 \
            -P 3306 \
            -u root \
            -proot \
            -e "SELECT VERSION();"


      # Step 4: Create original Student table
      - name: Create Student Table
        run: |
          mysql \
            -h 127.0.0.1 \
            -P 3306 \
            -u root \
            -proot <<'SQL'

          CREATE DATABASE IF NOT EXISTS CollegeDB;

          USE CollegeDB;

          DROP TABLE IF EXISTS Student;

          CREATE TABLE Student (
              StudentID INT PRIMARY KEY,
              StudentName VARCHAR(20) UNIQUE NOT NULL,
              DOB DATE NOT NULL,
              Gender VARCHAR(10) NOT NULL,
              DepartmentID INT NOT NULL
          );

          SQL


      # Step 5: Run student's solution
      - name: Run Student Solution
        run: |
          mysql \
            -h 127.0.0.1 \
            -P 3306 \
            -u root \
            -proot \
            < solution.sql


      # Step 6: Run tests
      - name: Run SQL Tests
        run: |
          mysql \
            -h 127.0.0.1 \
            -P 3306 \
            -u root \
            -proot \
            < test.sql
